shared:
  image: node:14
    
jobs:
  A:
    requires: [ ~commit ]
    steps:
      - show: echo 'A'
  B:
    requires: [ ~commit ]
    steps:
      - show: echo 'B'
      - sleep: sleep 180
  C:
    requires: [ ~commit ]
    steps:
      - show: echo 'C'
      - sleep: sleep 15
  D:
    requires: [ ~A, B, C]
    steps:
      - show: echo 'D'
      - sleep: sleep 90
